export const CHARGES = [
  { cat:"Assault", name:"Affray / Brawling", sentenceType:"Com Serv", notes:"A fight between 2 individuals or more in a public place that disturbs the peace." },
  { cat:"Assault", name:"Assault Emergency Services", sentenceType:"Indictable", notes:"Causing or attempting to cause injury to a first responder while performing their duties." },
  { cat:"Assault", name:"Assault on Public Officer", sentenceType:"Indictable", notes:"Causing or attempting to cause injury to a public officer while performing their duties." },
  { cat:"Assault", name:"Murder (NPC)", sentenceType:"Com Serv", notes:"Ending a local life with the intention of doing so." },
  { cat:"Assault", name:"Recklessly Or Intentionally Causing Injury", sentenceType:"Com Serv", notes:"Causing or attempting to cause serious injury through reckless or intentional actions." },
  { cat:"Assault", name:"Recklessly Or Intentionally Causing Serious Injury", sentenceType:"Indictable", notes:"Causing or attempting to cause serious injury through reckless or intentional actions." },

  { cat:"Conduct", name:"Breach of Enforced Outlaw Order", sentenceType:"Indictable", notes:"Violating a court order prohibiting criminal or dangerous activities." },
  { cat:"Conduct", name:"Conduct Endangering Life", sentenceType:"Com Serv", notes:"Behaviour that places or may place someone's life in danger." },
  { cat:"Conduct", name:"Criminal Damage", sentenceType:"Com Serv", notes:"Intentionally and without lawful excuse destroys or damages property." },
  { cat:"Conduct", name:"Disturb the Peace", sentenceType:"Com Serv", notes:"Umbrella for language, aggressive behavior, brawling." },
  { cat:"Conduct", name:"Drunk in a Public Place", sentenceType:"Com Serv", notes:"Drunk and disorderly in public." },
  { cat:"Conduct", name:"Obscene, Indecent, Threatening Language and Behaviour in Public", sentenceType:"Com Serv", notes:"Language or behaviour deemed obscene, indecent or threatening." },
  { cat:"Conduct", name:"Offensive Language in a Public Place", sentenceType:"Com Serv", notes:"Language deemed offensive and abusive." },
  { cat:"Conduct", name:"Offensive or Indecent Behaviour", sentenceType:"Com Serv", notes:"Indecent, offensive or insulting behaviour." },
  { cat:"Conduct", name:"Unlawful Assembly", sentenceType:"Com Serv", notes:"Large group intent on disturbing the peace." },

  { cat:"Custody", name:"Aid in Escape of Lawful Custody", sentenceType:"Indictable", notes:"Aiding someone in custody to escape police." },
  { cat:"Custody", name:"Escape Lawful Custody", sentenceType:"Indictable", notes:"Escaping police once placed in custody." },
  { cat:"Custody", name:"Resist Arrest", sentenceType:"Indictable", notes:"Attempting to free oneself from police custody." },

  { cat:"Theft", name:"Armed Robbery", sentenceType:"Indictable", notes:"Aggravated theft involving a weapon." },
  { cat:"Theft", name:"Attempted Robbery", sentenceType:"Com Serv", notes:"Attempted aggravated theft involving a weapon." },
  { cat:"Theft", name:"Breaking and Entering", sentenceType:"Com Serv", notes:"Unlawfully entering a building or structure." },
  { cat:"Theft", name:"Burglary", sentenceType:"Indictable", notes:"Stealing from a property." },
  { cat:"Theft", name:"Going Equipped for Stealing", sentenceType:"Com Serv", notes:"Possession of implements for stealing." },
  { cat:"Theft", name:"Robbery", sentenceType:"Indictable", notes:"Theft from a person." },
  { cat:"Theft", name:"Theft by Finding", sentenceType:"Com Serv", notes:"Theft of seemingly abandoned asset without checking." },
  { cat:"Theft", name:"Theft of a Government Service Vehicle (EMS+DPS)", sentenceType:"Indictable", notes:"Stealing an emergency vehicle." },
  { cat:"Theft", name:"Theft of a Motor Vehicle", sentenceType:"Com Serv", notes:"Stealing a civilian vehicle." },
  { cat:"Theft", name:"Theft on water or at sea (Piracy)", sentenceType:"Indictable", notes:"Stealing a watercraft at sea." },

  { cat:"Traffic", name:"Dangerous Driving", sentenceType:"Com Serv", notes:"Aggressive and incompetent driving, often seen in evasion." },
  { cat:"Traffic", name:"Dangerous Driving Causing Serious Injury", sentenceType:"Com Serv", notes:"Erratic driving resulting in injury." },
  { cat:"Traffic", name:"Drive Motor Vehicle in Menacing Manner", sentenceType:"Com Serv", notes:"Driving in a threatening manner." },
  { cat:"Traffic", name:"Driving Never Licensed", sentenceType:"Com Serv", notes:"Follow up after warned to get licence." },
  { cat:"Traffic", name:"Driving Whilst Disqualified", sentenceType:"Com Serv", notes:"Driving while licence is disqualified." },
  { cat:"Traffic", name:"Engaging in a Police Pursuit / Evade Police", sentenceType:"Indictable", notes:"Failing to stop and attempting to escape police with lights and sirens active." },
  { cat:"Traffic", name:"Fail to Stop and Render Assistance (Hit & Run)", sentenceType:"Com Serv", notes:"Failing to stay after a collision." },
  { cat:"Traffic", name:"Failure to stop for an Enforcement Vehicle (Non-Police)", sentenceType:"Indictable", notes:"Failure to stop for Sheriff or VicRoads." },
  { cat:"Traffic", name:"Fail to Stop for Police", sentenceType:"Com Serv", notes:"Deliberately ignoring attempts to stop." },
  { cat:"Traffic", name:"Negligent Driving", sentenceType:"Com Serv", notes:"Driving in a negligent manner." },
  { cat:"Traffic", name:"Organising an unauthorised Race/Trial", sentenceType:"Indictable", notes:"Arranging a race/trial without authorisation." },
  { cat:"Traffic", name:"Participating in an unauthorised Race/Trial", sentenceType:"Com Serv", notes:"Taking part in a race/trial without authorisation." },
  { cat:"Traffic", name:"Owner Fail to provide details of driver of their motor vehicle", sentenceType:"Com Serv", notes:"Owner fails to provide driver details." },
  { cat:"Traffic", name:"XPCA: Drug Detected in Oral Fluid, Blood or Urine", sentenceType:"Com Serv", notes:"Narcotics found in samples." },
  { cat:"Traffic", name:"XPCA: High Range: BAC. of 0.15 or Above", sentenceType:"Com Serv", notes:"BAC 0.15 or higher." },
  { cat:"Traffic", name:"XPCA: Low Range: BAC. of 0.05 to less than 0.08", sentenceType:"Com Serv", notes:"BAC 0.05 to less than 0.08." },
  { cat:"Traffic", name:"XPCA: Mid Range: BAC. of 0.08 to less than 0.15", sentenceType:"Com Serv", notes:"BAC 0.08 to less than 0.15." },
  { cat:"Traffic", name:"XPCA: Refuse to Provide Samples: Breath, Blood or Urine", sentenceType:"Com Serv", notes:"Refusing to provide samples." },
  { cat:"Traffic", name:"XPCA: Novice Range: BAC. More Than Zero for Learner, P1 or P2", sentenceType:"Com Serv", notes:"BAC greater than 0.00 for novice." },

  { cat:"Weapons", name:"Assault with a Deadly Weapon", sentenceType:"Indictable", notes:"Inflicting harm with a weapon capable of serious harm." },
  { cat:"Weapons", name:"Carry a Weapon Concealed without Legal Authority", sentenceType:"Com Serv", notes:"Carrying a firearm concealed without appropriate authority." },
  { cat:"Weapons", name:"Carry a Weapon Openly (Open Carry) Without Legal Authority", sentenceType:"Com Serv", notes:"Carrying or brandishing a weapon visibly without authority." },
  { cat:"Weapons", name:"Discharge of weapon in a public place", sentenceType:"Indictable", notes:"Firing a weapon in public." },
  { cat:"Weapons", name:"Non Compliance with a Firearm Prohibition Order", sentenceType:"Indictable", notes:"FPO subject in possession of a firearm." },
  { cat:"Weapons", name:"Possess an Accessory or Ammunition Without Legal Authority", sentenceType:"Com Serv", notes:"Possession of illegal accessories or ammo without authority." },
  { cat:"Weapons", name:"Possess an Imitation Weapon Without Legal Authority", sentenceType:"Com Serv", notes:"Possessing a weapon made to look like a firearm." },
  { cat:"Weapons", name:"Possess a Handgun Without Legal Authority", sentenceType:"Com Serv", notes:"Possession of handguns without a licence." },
  { cat:"Weapons", name:"Possess a Controlled Weapon/Dangerous Article Without Legal Authority", sentenceType:"Com Serv", notes:"Possession of controlled weapon without lawful excuse." },
  { cat:"Weapons", name:"Possess a Prohibited Weapon Without Legal Authority", sentenceType:"Com Serv", notes:"Possession of prohibited weapons such as switchblades." },
  { cat:"Weapons", name:"Possess an illegal Handgun or Longarm Without Legal Authority", sentenceType:"Indictable", notes:"Possession of illegal handgun or longarm." },
  { cat:"Weapons", name:"Possess an Offensive Weapon (Explosive) Without Legal Authority", sentenceType:"Indictable", notes:"Possession of explosives like C4, molotovs, grenades." },
  { cat:"Weapons", name:"Trafficking / Illegal Sale of a Weapon (Individual / Small Scale)", sentenceType:"Indictable", notes:"Small scale sale or purchase of firearms." },
  { cat:"Weapons", name:"Trafficking / Illegal Sale of a Weapon (Large Scale)", sentenceType:"Indictable", notes:"Large quantity sale or purchase of firearms." },

  { cat:"Drug", name:"Cultivation of Narcotic Plants", sentenceType:"Com Serv", notes:"Growing or picking illegal plants." },
  { cat:"Drug", name:"Manufacturing a Drug of Dependence", sentenceType:"Com Serv", notes:"In process of making narcotics." },
  { cat:"Drug", name:"Possession of Implements for Trafficking a Drug of Dependence", sentenceType:"Com Serv", notes:"Possession of items to commit trafficking." },
  { cat:"Drug", name:"Possession of a Drug of Dependence", sentenceType:"Com Serv", notes:"Possession of narcotics under thresholds." },
  { cat:"Drug", name:"Possession of a Large Quantity Drug of Dependence", sentenceType:"Indictable", notes:"Possession of large quantity of narcotics." },
  { cat:"Drug", name:"Trafficking a Drug of Dependence", sentenceType:"Indictable", notes:"Sale or purchase of illegal narcotics." },

  { cat:"Fraud", name:"Bribery", sentenceType:"Com Serv", notes:"Attempt to persuade judgement and integrity with money or actions." },
  { cat:"Fraud", name:"Credit Card Fraud - Low", sentenceType:"Com Serv", notes:"Possession of 0 to 100 false credit cards." },
  { cat:"Fraud", name:"Credit Card Fraud - Moderate or Trafficking", sentenceType:"Indictable", notes:"100 to 500 counterfeit cards or sale thereof." },
  { cat:"Fraud", name:"Credit Card Fraud - High or High Trafficking", sentenceType:"Indictable", notes:"500+ counterfeit cards or sale thereof." },
  { cat:"Fraud", name:"False Accounting", sentenceType:"Com Serv", notes:"Changing figures or writing false info in records." },
  { cat:"Fraud", name:"False Statement by Company Directors etc", sentenceType:"Com Serv", notes:"Purposely incorrect and misleading statement by director." },
  { cat:"Fraud", name:"Obtain Property / Financial Advantage by Deception", sentenceType:"Com Serv", notes:"Fraud such as insurance fraud." },
  { cat:"Fraud", name:"State False Name and Address / Fraudulent Identification", sentenceType:"Com Serv", notes:"Not providing correct name and address." },

  { cat:"Other", name:"(Insp+ Auth) Operate an Aircraft for the purposes of crime", sentenceType:"Indictable", notes:"Operating an aircraft for crimes." },
  { cat:"Other", name:"(Insp+ Auth) Operate an Aircraft in an unsafe or unauthorised manner", sentenceType:"Indictable", notes:"Operating aircraft in unsafe or unauthorised manner." },
  { cat:"Other", name:"Animal Cruelty", sentenceType:"Indictable", notes:"Animal abuse." },
  { cat:"Other", name:"Arson", sentenceType:"Com Serv", notes:"Deliberately setting fire to property." },
  { cat:"Other", name:"Attempted Murder (Player)", sentenceType:"Indictable", notes:"Attempting to end a player's life with intent." },
  { cat:"Other", name:"Attempted Murder on Emergency Services", sentenceType:"Indictable", notes:"Attempted murder of Police, Fire, Ambulance." },
  { cat:"Other", name:"Attempted Murder on Public Officer", sentenceType:"Indictable", notes:"Attempted murder of public officer." },
  { cat:"Other", name:"Commit Act of Terror", sentenceType:"Indictable", notes:"Act of terror for political or religious gain." },
  { cat:"Other", name:"Suspicion to Commit an Act of Terror", sentenceType:"Indictable", notes:"Suspicion to commit an act of terror." },
  { cat:"Other", name:"Member of a Terrorist Organisation", sentenceType:"Indictable", notes:"Member of a terrorist organisation." },
  { cat:"Other", name:"Cyber Bullying or Stalking", sentenceType:"Com Serv", notes:"Electronic communication to bully or stalk." },
  { cat:"Other", name:"Failure to comply with a lawful direction from Police", sentenceType:"Com Serv", notes:"Willful failure to comply with police direction." },
  { cat:"Other", name:"Failure to Comply with a Noise Abatement Notice", sentenceType:"Com Serv", notes:"Failing to comply with noise guidelines." },
  { cat:"Other", name:"False Arrest", sentenceType:"Indictable", notes:"Arresting someone under false pretences." },
  { cat:"Other", name:"Hinder or Obstruct Police", sentenceType:"Com Serv", notes:"Obstructing police from enforcing the law." },
  { cat:"Other", name:"Impersonate Government Employee", sentenceType:"Indictable", notes:"Tricking others into believing you are AFP or government." },
  { cat:"Other", name:"Impersonation of Police Officers", sentenceType:"Indictable", notes:"Tricking others into believing you are police." },
  { cat:"Other", name:"Indecent Exposure", sentenceType:"Com Serv", notes:"Exposing yourself to the public." },
  { cat:"Other", name:"Kidnapping", sentenceType:"Indictable", notes:"Abducting someone and holding them captive." },
  { cat:"Other", name:"Make False Report or False Statements (Perjury)", sentenceType:"Com Serv", notes:"Lying to court or reporting a false event." },
  { cat:"Other", name:"Make Threats to Kill", sentenceType:"Indictable", notes:"Making threats toward another person's life." },
  { cat:"Other", name:"Make, Use or Possess False Document (Includes Money)", sentenceType:"Com Serv", notes:"Producing or using illegitimate document or money." },
  { cat:"Other", name:"Manslaughter (Player)", sentenceType:"Indictable", notes:"Ending someone's life without intention." },
  { cat:"Other", name:"Murder (Player)", sentenceType:"Indictable", notes:"Ending a player's life with intention." },
  { cat:"Other", name:"Murder (Emergency Service Worker)", sentenceType:"Indictable", notes:"Ending a first responder's life with intention." },
  { cat:"Other", name:"Obstruct or Hinder Road Safety Camera Operator", sentenceType:"Indictable", notes:"Deliberate damage to mobile speed camera." },
  { cat:"Other", name:"Proceeds of Crime", sentenceType:"Com Serv", notes:"Money or objects obtained through crime." },
  { cat:"Other", name:"Trespass", sentenceType:"Indictable", notes:"Entering property or area without permission." },
  { cat:"Other", name:"Unlawful landing and parking of an Aircraft outside designated zones", sentenceType:"Indictable", notes:"Landing or parking aircraft outside designated zones." },
  { cat:"Other", name:"Wear or Carry an article of disguise with unlawful intent", sentenceType:"Com Serv", notes:"Mask or helmet covering identity with intent for crime." },
  { cat:"Other", name:"Vandalism of a Government Building", sentenceType:"Indictable", notes:"Damage or defacement of government buildings." },
  { cat:"Other", name:"Vandalism of Public Property", sentenceType:"Com Serv", notes:"Damage or defacement of public property." },
  { cat:"Other", name:"Intent to Commit Crime - Cyber", sentenceType:"Com Serv", notes:"Using digital platforms to solicit or promote criminal activity." },
  { cat:"Other", name:"Malicious Tampering - Cyber", sentenceType:"Com Serv", notes:"Intentional interference with digital systems or data." },

  { cat:"Court", name:"Contempt of Court", sentenceType:"NI/I", notes:"Only if ordered by the court." },
  { cat:"Court", name:"Failure to Attend", sentenceType:"Indictable", notes:"Only if ordered by the court." },
  { cat:"Court", name:"Breach of Bail", sentenceType:"Indictable", notes:"Only if ordered by the court." },
  { cat:"Court", name:"Court-Ordered Fee", sentenceType:"Indictable", notes:"Only if ordered by the court." },
];

export const REPORT_TYPE_LABEL = {
  arrest: "ARREST REPORT",
  criminal_warrant: "CRIMINAL WARRANT",
  traffic_warrant: "TRAFFIC WARRANT",
  field_contact: "FIELD CONTACT",
  search_seizure: "SEARCH AND SEIZURE REPORT"
};
